src/Entity/Tender.php
<?php

declare(strict_types = 1);

namespace App\Entity;

use App\Repository\TenderRepository;
use Carbon\Carbon;
use DateInterval;
use DateTimeImmutable;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\IdGenerator\UuidGenerator;
use Symfony\Component\Uid\Uuid;

#[ORM\Entity(repositoryClass: TenderRepository::class)]
class Tender
{
    #[ORM\Id]
    #[ORM\GeneratedValue(strategy: 'CUSTOM')]
    #[ORM\Column(type: 'uuid', unique: true)]
    #[ORM\CustomIdGenerator(UuidGenerator::class)]
    private Uuid $id;

    #[ORM\ManyToOne(targetEntity: Asset::class, inversedBy: 'tenders')]
    private ?Asset $asset = null;

    #[ORM\Column(type: 'datetime_immutable')]
    private DateTimeImmutable $createdAt;

    #[ORM\OneToOne(targetEntity: Bid::class, cascade: ['persist', 'remove'])]
    private ?Bid $bid = null;

    #[ORM\Column(type: 'integer')]
    private int $durationInDays = 30;

    #[ORM\Column(type: 'datetime_immutable')]
    private DateTimeImmutable $startAt;

    #[ORM\Column(type: 'datetime_immutable')]
    private DateTimeImmutable $endAt;

    public function __construct()
    {
        $this->createdAt = new DateTimeImmutable();
    }

    public function getId(): ?Uuid
    {
        return $this->id;
    }

    public function getAsset(): ?Asset
    {
        return $this->asset;
    }

    public function setAsset(?Asset $asset): self
    {
        $this->asset = $asset;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeImmutable $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getBid(): ?Bid
    {
        return $this->bid;
    }

    public function setBid(?Bid $bid): self
    {
        $this->bid = $bid;

        return $this;
    }

    public function getDurationInDays(): ?int
    {
        return $this->durationInDays;
    }

    public function setDurationInDays(int $durationInDays): self
    {
        $this->durationInDays = $durationInDays;

        return $this;
    }

    public function getStartAt(): ?\DateTimeImmutable
    {
        return $this->startAt;
    }

    public function setStartAt(\DateTimeImmutable $startAt): self
    {
        $this->startAt = $startAt;

        return $this;
    }

    public function getEndAt(): ?\DateTimeImmutable
    {
        return $this->endAt;
    }

    public function setEndAt(\DateTimeImmutable $endAt): self
    {
        $this->endAt = $endAt;

        return $this;
    }

    public function getTimeUntilEnd(): float|int
    {
        $end = Carbon::parse($this->endAt);

        return $end->diffInMilliseconds();
    }

    public function getTimeUntilEndInInterval(): DateInterval
    {
        $end = Carbon::parse($this->endAt);

        return $end->diffAsCarbonInterval()
            ->toDateInterval();
    }

    public function getIsActive(): bool
    {
        $start = Carbon::parse($this->startAt);
        $end = Carbon::parse($this->endAt);

        return Carbon::now()->isBetween($start, $end);
    }

    public function getIsStartPendding(): bool
    {
        $start = Carbon::parse($this->startAt);

        return Carbon::now()->isBefore($start);
    }

    public function getIsComplete(): bool
    {
        $end = Carbon::parse($this->endAt);

        return Carbon::now()->isAfter($end);
    }
}

src/Entity/User.php
<?php

declare(strict_types = 1);

namespace App\Entity;

use App\Repository\UserRepository;
use DateTimeImmutable;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Stringable;
use Symfony\Bridge\Doctrine\IdGenerator\UuidGenerator;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Uid\Uuid;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[ORM\Table(name: '`user`')]
#[UniqueEntity(fields: ['email'], message: 'There is already an account with this email')]
class User implements UserInterface, PasswordAuthenticatedUserInterface, Stringable
{
    #[ORM\Id]
    #[ORM\GeneratedValue(strategy: 'CUSTOM')]
    #[ORM\Column(type: 'uuid', unique: true)]
    #[ORM\CustomIdGenerator(UuidGenerator::class)]
    private Uuid $id;

    #[ORM\Column(type: 'string', length: 255)]
    private string $firstName;

    #[ORM\Column(type: 'string', length: 255)]
    private string $lastName;

    /**
     * @var ArrayCollection<int, Asset>
     */
    #[ORM\OneToMany(mappedBy: 'owner', targetEntity: Asset::class)]
    private Collection $assets;

    #[ORM\Column(type: 'string', length: 180, unique: true)]
    private string $email;

    #[ORM\Column(type: 'json')]
    private array $roles = [];

    #[ORM\Column(type: 'string')]
    private string $password;

    #[ORM\Column(type: 'text')]
    private string $avatar;

    /** @var Collection<int, SocialAuth> */
    #[ORM\OneToMany(mappedBy: 'owner', targetEntity: SocialAuth::class)]
    private Collection $socialAuths;

    #[ORM\Column(type: 'uuid', unique: true)]
    private Uuid $token;

    #[ORM\Column(type: 'boolean')]
    private bool $isEnabled = false;

    /**
     * @var ArrayCollection<int, Message>
     */
    #[ORM\OneToMany(mappedBy: 'owner', targetEntity: Message::class)]
    private Collection $messages;

    /**
     * @var ArrayCollection<int, Conversation>
     */
    #[ORM\ManyToMany(targetEntity: Conversation::class, mappedBy: 'users', cascade: ['persist'])]
    private Collection $conversations;

    #[ORM\Column(type: 'datetime_immutable')]
    private DateTimeImmutable $createdAt;

    /**
     * @var ArrayCollection<int, AssetView>
     */
    #[ORM\OneToMany(mappedBy: 'owner', targetEntity: AssetView::class)]
    private Collection $assetViews;

    /**
     * @var ArrayCollection<int, Insight>
     */
    #[ORM\OneToMany(mappedBy: 'owner', targetEntity: Insight::class)]
    private Collection $insights;

    /**
     * @var ArrayCollection<int, Review>
     */
    #[ORM\OneToMany(mappedBy: 'author', targetEntity: Review::class,)]
    private Collection $ownedReviews;

    /**
     * @var ArrayCollection<int, Review>
     */
    #[ORM\OneToMany(mappedBy: 'user', targetEntity: Review::class)]
    private Collection $reviews;

    /**
     * @var ArrayCollection<int, Reaction>
     */
    #[ORM\OneToMany(mappedBy: 'owner', targetEntity: Reaction::class)]
    private Collection $reactions;

    /**
     * @var ArrayCollection<int, Bookmark>
     */
    #[ORM\OneToMany(mappedBy: 'owner', targetEntity: Bookmark::class)]
    private Collection $bookmarks;

    /**
     * @var ArrayCollection<int, Bid>
     */
    #[ORM\OneToMany(mappedBy: 'owner', targetEntity: Bid::class)]
    private Collection $bids;

    public function __construct()
    {
        $this->insights = new ArrayCollection();
        $this->ownedReviews = new ArrayCollection();
        $this->reviews = new ArrayCollection();
        $this->reactions = new ArrayCollection();
        $this->bookmarks = new ArrayCollection();
        $this->bids = new ArrayCollection();
        $this->token = Uuid::v4();
        $this->socialAuths = new ArrayCollection();
        $this->assets = new ArrayCollection();
        $this->conversations = new ArrayCollection();
        $this->messages = new ArrayCollection();
        $this->assetViews = new ArrayCollection();
        $this->createdAt = new DateTimeImmutable();
    }

    public function __toString(): string
    {
        return $this->getFullName();
    }

    /**
     * @return ArrayCollection<int, Insight>
     */
    public function getInsights(): Collection
    {
        return $this->insights;
    }

    public function addInsight(Insight $insight): self
    {
        if (! $this->insights->contains($insight)) {
            $this->insights[] = $insight;
            $insight->setOwner($this);
        }

        return $this;
    }

    public function removeInsight(Insight $insight): self
    {
        // set the owning side to null (unless already changed)
        if ($this->insights->removeElement($insight) && $insight->getOwner() === $this) {
            $insight->setOwner(null);
        }

        return $this;
    }

    /**
     * @return ArrayCollection<int, Review>
     */
    public function getOwnedReviews(): Collection
    {
        return $this->ownedReviews;
    }

    public function addOwnedReview(Review $ownedReview): self
    {
        if (! $this->ownedReviews->contains($ownedReview)) {
            $this->ownedReviews[] = $ownedReview;
            $ownedReview->setAuthor($this);
        }

        return $this;
    }

    public function removeOwnedReview(Review $ownedReview): self
    {
        // set the owning side to null (unless already changed)
        if ($this->ownedReviews->removeElement($ownedReview) && $ownedReview->getAuthor() === $this) {
            $ownedReview->setAuthor(null);
        }

        return $this;
    }

    /**
     * @return ArrayCollection<int, Review>
     */
    public function getReviews(): Collection
    {
        return $this->reviews;
    }

    public function addReview(Review $review): self
    {
        if (! $this->reviews->contains($review)) {
            $this->reviews[] = $review;
            $review->setUser($this);
        }

        return $this;
    }

    public function removeReview(Review $review): self
    {
        // set the owning side to null (unless already changed)
        if ($this->reviews->removeElement($review) && $review->getUser() === $this) {
            $review->setUser(null);
        }

        return $this;
    }

    /**
     * @return Collection<int, Reaction>
     */
    public function getReactions(): Collection
    {
        return $this->reactions;
    }

    public function addReaction(Reaction $reaction): self
    {
        if (! $this->reactions->contains($reaction)) {
            $this->reactions[] = $reaction;
            $reaction->setOwner($this);
        }

        return $this;
    }

    public function removeReaction(Reaction $reaction): self
    {
        // set the owning side to null (unless already changed)
        if ($this->reactions->removeElement($reaction) && $reaction->getOwner() === $this) {
            $reaction->setOwner(null);
        }

        return $this;
    }

    /**
     * @return Collection<int, Bookmark>
     */
    public function getBookmarks(): Collection
    {
        return $this->bookmarks;
    }

    public function addBookmark(Bookmark $bookmark): self
    {
        if (! $this->bookmarks->contains($bookmark)) {
            $this->bookmarks[] = $bookmark;
            $bookmark->setOwner($this);
        }

        return $this;
    }

    public function removeBookmark(Bookmark $bookmark): self
    {
        // set the owning side to null (unless already changed)
        if ($this->bookmarks->removeElement($bookmark) && $bookmark->getOwner() === $this) {
            $bookmark->setOwner(null);
        }

        return $this;
    }

    /**
     * @return Collection<int, Bid>
     */
    public function getBids(): Collection
    {
        return $this->bids;
    }

    public function addBid(Bid $bid): self
    {
        if (! $this->bids->contains($bid)) {
            $this->bids[] = $bid;
            $bid->setOwner($this);
        }

        return $this;
    }

    public function removeBid(Bid $bid): self
    {
        // set the owning side to null (unless already changed)
        if ($this->bids->removeElement($bid) && $bid->getOwner() === $this) {
            $bid->setOwner(null);
        }

        return $this;
    }

    public function getId(): ?Uuid
    {
        return $this->id;
    }

    public function getToken(): ?Uuid
    {
        return $this->token;
    }

    public function setToken(Uuid $token): void
    {
        $this->token = $token;
    }

    public function isIsEnabled(): ?bool
    {
        return $this->isEnabled;
    }

    public function setIsEnabled(bool $isEnabled): self
    {
        $this->isEnabled = $isEnabled;

        return $this;
    }

    public function getFullName(): string
    {
        return $this->firstName . ' ' . $this->lastName;
    }

    public function getFirstName(): ?string
    {
        return $this->firstName;
    }

    public function setFirstName(string $firstName): self
    {
        $this->firstName = $firstName;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->lastName;
    }

    public function setLastName(string $lastName): self
    {
        $this->lastName = $lastName;

        return $this;
    }

    public function getEmail(): string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * @return ArrayCollection<int, Asset>
     */
    public function getAssets(): Collection
    {
        return $this->assets;
    }

    public function addAsset(Asset $asset): self
    {
        if (! $this->assets->contains($asset)) {
            $this->assets[] = $asset;
            $asset->setOwner($this);
        }

        return $this;
    }

    public function removeAsset(Asset $asset): self
    {

templates/macro/asset.macro.twig
{% macro card(
    asset,
    carousel = true,
    detailed = false
    ) %}
    {% import "macro/component.macro.twig" as component %}

    <div class="card h-100 position-relative mb-3 shadow-sm">
        {% if carousel %}
            <turbo-frame id="asset-images" src="{{ path('asset_images', {id: asset.id}) }}" loading="lazy">
                <div class="d-flex justify-content-center align-items-center img-loading-placeholder">
                    <div class="spinner-border" role="status">
                        <span class="visually-hidden">Loading...</span>
                    </div>
                </div>
            </turbo-frame>
        {% endif %}
        <div class="card-body pb-0 pt-2 position-relative">
            <div class="d-flex justify-content-between align-items-center mb-2 mt-2">
                <div class="me-2">
                        {{ include('profile/_avatar-profile-link.html.twig', {
                            user: asset.owner
                        }) }}
                </div>
                <div>
                    <a href="{{ path('app_asset_show', {id: asset.id}) }}" class="custom-link" target="_blank">
                        <div class="h5 m-0">{{ asset.title|capitalize }}</div>
                    </a>
                </div>
            </div>
            <div class="position-absolute top-0 start-0 translate-middle-y d-flex justify-content-evenly w-100"
                 style="z-index: 100">
                <span {{ component.tooltip('top', 'sqm'|trans ) }}
                      class="h5 letter-spacing-1 mb-0 badge badge-pill bg-white text-black">{{ asset.sqm }} <span>m<sup>2</sup></span></span>
                <span {{ component.tooltip('top', 'term'|trans ) }}
                      class="h5 letter-spacing-1 mb-0 badge badge-pill bg-white text-black">{{ asset.term|trans|capitalize }}</span>
                {% if  asset.tender and asset.tender.isActive and asset.tender.bid %}
                    <div id="tender-price-{{ asset.tender.id }}" {{ turbo_stream_listen('tender-price') }}>
                        {{ include('asset/_price.html.twig', {
                            bid: asset.tender.bid
                        }) }}
                    </div>
                {% elseif asset.tender and asset.tender.isComplete %}
                    <span {{ component.tooltip('top', 'closing-bid'|trans ) }}
                      class="h5 letter-spacing-1 mb-0 badge badge-pill bg-white text-black">{{ asset.tender.bid.amount|format_currency(asset.currency) }}</span>
                {% else %}
                    <span {{ component.tooltip('top', 'price'|trans ) }}
                      class="h5 letter-spacing-1 mb-0 badge badge-pill bg-white text-black">{{ asset.price|format_currency(asset.currency) }}</span>
                {% endif %}
            </div>
            {% if detailed %}
                <div class="mt-2">{{ asset.description|raw }}</div>
            {% else %}
                <div class="mt-2">{{ asset.description|slice(0,100) }}...</div>
            {% endif %}
        </div>
        <div class="card-footer bg-white">
            <div class="d-flex justify-content-between">
                <div id="asset-reaction-{{ asset.id }}" {{ turbo_stream_listen('reaction') }}>
                    {{ include('reaction/_badges.html.twig', {
                        asset: asset
                    }) }}
                </div>
                {% if app.user != asset.owner %}
                    <div id="asset-bookmark-{{ asset.id }}" {{ turbo_stream_listen('bookmark') }}>
                        {{ include('bookmark/_button.html.twig', {
                            path: path('add_bookmark', {id: asset.id})
                        }) }}
                    </div>
                {% endif %}
            </div>
        </div>
    </div>
{% endmacro %}


{% macro ownerCard(
    asset
    ) %}
    <div class="card position-relative shadow-sm">
        <div class="card-footer border-bottom border-top-0 bg-white d-flex justify-content-evenly w-100">
                <span class="badge bg-primary rounded-pill"><span
                            class="mdi mdi-heart-outline me-1"></span> {{ asset.likes|compact_notation }}</span>
            <span class="badge bg-primary rounded-pill"><span
                        class="mdi mdi-thumb-down me-1"></span>{{ asset.dislikes|compact_notation }}</span>
            <span class="badge bg-primary rounded-pill"><span
                        class="mdi mdi-bookmark-outline me-1"></span>{{ asset.bookmarks.count|compact_notation }}</span>
            <span class="badge bg-primary rounded-pill"><span
                        class="mdi mdi-eye me-1"></span>{{ asset.views.count|compact_notation }}</span>
        </div>
        <div class="card-body pt-2 position-relative">
            <div class="d-flex justify-content-between align-items-center mb-2 mt-2">
                <div>
                    <a href="{{ path('app_owner_asset_show', {id: asset.id}) }}"
                       class="btn btn-link p-0">
                        <div class="h5 m-0">{{ asset.title|capitalize }}</div>
                    </a>
                    <div class="mt-2">{{ asset.description|slice(0,100) }}...</div>
                </div>
            </div>
        </div>
        <div class="card-footer bg-white">
            <div class="d-flex justify-content-end">
                {% if not asset.tender %}
                    <a href="{{ path('new_tender', {id: asset.id}) }}"
                       class="btn btn-primary w-100">
                        {{ 'start-tender'|trans }}
                    </a>
                {% elseif asset.tender.isActive %}
                    AUCTION ACTIVE
                {% endif %}
            </div>
        </div>
        <div class="card-footer bg-white text-end">
            <div class="small text-muted">{{ asset.createdAt|date }}</div>
        </div>
    </div>
{% endmacro %}

templates/macro/component.macro.twig
{% macro modal(
    modalId,
    frameId,
    path,
    title,
    target = '_top',
    isBody = true
    ) %}

    <div class="modal fade" id="{{ modalId }}" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1"
         aria-labelledby="staticBackdropLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="staticBackdropLabel">{{ title }}</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <turbo-frame class="{% if isBody %} modal-body {% endif %}" id="{{ frameId }}" src="{{ path }}" target="{{ target }}" loading="lazy">
                    <div class="d-flex min-vh-50 justify-content-center align-items-center">
                        <div class="spinner-border" role="status">
                            <span class="visually-hidden">Loading...</span>
                        </div>
                    </div>
                </turbo-frame>
            </div>
        </div>
    </div>

{% endmacro %}

{% macro tooltip(
    position,
    title,
    ) %}
    data-bs-toggle="tooltip" data-bs-placement="{{ position }}" title="{{ title|trans }}"
{% endmacro %}


{% macro iconBtnLink(
    route,
    icon
    ) %}

{% endmacro %}

templates/macro/conversation.macro.twig
{% macro item(conversation, hasLastMessage = true) %}

    {% import "macro/user.macro.twig" as user %}

    <div class="card mb-2">
        <div class="card-body">
            <div>
                <div>{{ conversation.title }}</div>
                {{ user.avatar(conversation.users) }}
            </div>
            {% if hasLastMessage and conversation.messages|last %}
                <div class="border-top py-1 my-1 text-muted small">{{ conversation.messages|last|slice(0,50) }}...</div>
            {% endif %}
            <a class="stretched-link"
               href="{{ path('conversation', {id: conversation.id}) }}"></a>
        </div>
    </div>
{% endmacro %}


{% macro message(message) %}
    {% if app.user == message.owner %}
        <div class="d-flex justify-content-between">
            <div data-bs-toggle="tooltip" data-bs-placement="right" title="{{ message.owner.fullName }}">
                <img class="rounded-circle shadow-sm me-2" height="40" src="{{ message.owner.avatar }}"/>
            </div>
            <div>
                <div class="bg-grey rounded-2 p-2">{{ message.content }}</div>
                <div class="xtra-small text-muted">{{ message.createdAt|format_datetime() }}</div>
            </div>
        </div>
    {% else %}
        <div class="d-flex justify-content-between">
            <div>
                <div class="bg-grey rounded-2 p-2">{{ message.content }}</div>
                <div class="xtra-small text-muted">{{ message.createdAt|format_datetime() }}</div>
            </div>
            <div data-bs-toggle="tooltip" data-bs-placement="right" title="{{ message.owner.fullName }}">
                <img class="rounded-circle shadow-sm ms-2" height="40" src="{{ message.owner.avatar }}"/>
            </div>
        </div>
    {% endif %}
{% endmacro %}

templates/macro/user.macro.twig
{% macro reviewCard(review) %}
    {% import "macro/user.macro.twig" as userMacro %}

    <div class="card mb-3">
        <div class="card-body">
            <div class="d-flex justify-content-between">
                <div>
                    {% if review.asset %}
                        <div>{{ 'tenent-of'|trans }} {{ review.asset.title }}</div>
                    {% endif %}
                    <div>{{ review.notes }}</div>
                </div>
                <div>
                    <span {{ userMacro.rating(review.rating) }}</span>
                    <div class="text-end text-muted small">
                        {{ review.createdAt|format_date(pattern='MMM yy') }}</div>
                </div>
            </div>
        </div>


    </div>
{% endmacro %}

{% macro rating(rating) %}
    <span data-bs-toggle="tooltip" data-bs-placement="top" title="{{ rating }}/5">
        {% for i in range(0.5, 5) %}
            <i class="bi {{ loop.index > rating ? 'bi-star text-muted' : 'bi-star-fill text-warning' }} fs-3"></i>
        {% endfor %}
    </span>
{% endmacro %}

{% macro avatar(users) %}
    <div class="avatars">
        {% for user in users %}
            {% if user != app.user %}
                <img alt="{{ user.fullName }}" data-bs-toggle="tooltip"
                     data-bs-placement="right" title="{{ user.fullName }}"
                     class="avatars__item" src="{{ user.avatar }}" height="45"/>
            {% endif %}
        {% endfor %}
    </div>
{% endmacro %}